FROM timberio/vector:0.24.2-debian as logshipper

RUN apt update \
    && apt install -y \
    gettext \
    && rm -rf /var/cache/apt

RUN rm -rf /etc/vector \
    && mkdir -p /etc/vector/certificates

COPY vector.yaml /etc/vector/
COPY templates/*.yaml.template /etc/vector/
COPY start.sh .

ENV LOG warn
ENV DISABLE false

ENTRYPOINT [ "bash" ]

CMD [ "start.sh" ]
